events {}

http {
    server {
        listen 443 ssl;  # Listen on HTTPS port
        server_name eklymova.42.fr;  # Domain name

        ssl_certificate /etc/nginx/ssl/tls.crt;   # Path to certificate
        ssl_certificate_key /etc/nginx/ssl/tls.key;  # Path to private key
        ssl_protocols TLSv1.2 TLSv1.3; # protocols

        root /var/www/html; #worldpress root folder
        index index.php index.html; #default index files

        location / {
            try_files $uri $uri/ /index.php?$args; #handle permalinks
        }

        location ~ \.php$ {
            include fastcgi_params; # Load FastCGI parameters
            fastcgi_pass wordpress:9000; # Send PHP requests to PHP-FPM
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # Full path to script
        }
    }
}